use std::collections::hash_map::DefaultHasher;
use std::fs;
use std::hash::{Hash, Hasher};
use std::path::{Path, PathBuf};

fn main() {
    // Tauri 资源/配置处理（必须调用，否则 generate_context! 找不到资源）
    tauri_build::build();

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_default();
    let manifest = PathBuf::from(&manifest_dir);
    let target_dir = manifest.join("target");

    let build_date = chrono::Local::now().format("%Y%m%d").to_string();

    // 源码指纹：仅纳入「真正影响产物的源文件/目录」。
    // 设计目标（用户要求）：同一份源码多次构建，版本号不升版；只有源码发生实际修改才升版。
    let signature = compute_signature(&manifest);

    // 历史状态：优先读 .build_state；首次迁移时从旧的 .build_count 取基准计数。
    let state_path = target_dir.join(".build_state");
    let (prev_date, prev_sig, prev_count) = read_state(&state_path);

    let count = if prev_date != build_date {
        1 // 跨天：版本日期部分已变化，当天构建次数从 1 起算
    } else if prev_sig == signature {
        prev_count // 源码未变：保持同一版本，不升版
    } else {
        prev_count + 1 // 源码已变：升版
    };

    let _ = fs::create_dir_all(&target_dir);
    let _ = fs::write(
        &state_path,
        format!("{} {} {}\n", build_date, signature, count),
    );

    // 版本常量写入 OUT_DIR（不在 src 目录内），models.rs 通过 include!(OUT_DIR) 引入。
    // 放在 OUT_DIR 可避免「生成文件落在 src 里 → rerun-if-changed 监听到自身变化 → 每次都重跑」的死循环。
    let out_dir = std::env::var("OUT_DIR").unwrap_or_default();
    let gen_path = PathBuf::from(&out_dir).join("generated_version.rs");
    let _ = fs::write(
        &gen_path,
        format!(
            "// AUTO-GENERATED by build.rs — DO NOT EDIT\n\
             // 编译期固定注入：构建日期 + 当天构建次数（如 1.0.20260723.2）\n\
             // 仅当源码实际变化时才 +1；同一份源码重复构建不升版（详见 build.rs）。\n\
             pub const APP_BUILD_VERSION: &str = \"1.0.{}.{}\";\n",
            build_date, count
        ),
    );

    // rerun-if-changed：只监听真实源码与关键配置。生成文件在 OUT_DIR，不在此列。
    // 关键：让 Cargo 在生成版本变化时重编译引用它的模块；
    //       其余源码变化时 build.rs 会重跑并重算指纹，决定是否升版。
    println!("cargo:rerun-if-changed=src");
    println!("cargo:rerun-if-changed=src-tauri/src");
    println!("cargo:rerun-if-changed=src-tauri/Cargo.toml");
    println!("cargo:rerun-if-changed=src-tauri/Cargo.lock");
    println!("cargo:rerun-if-changed=src-tauri/tauri.conf.json");
    println!("cargo:rerun-if-changed=package.json");
    println!("cargo:rerun-if-changed={}", gen_path.display());

    // 调试信息，便于在构建日志中核对升/不升版决策
    eprintln!(
        "[build] date={} signature={:016x} prev_count={} -> count={}",
        build_date, signature, prev_count, count
    );
}

/// 计算「源码指纹」：对真正影响产物的源目录与关键配置文件做内容哈希。
/// node_modules / dist / target / .git / generated_version.rs 等均排除。
fn compute_signature(manifest: &Path) -> u64 {
    let mut h = DefaultHasher::new();
    dir_signature(&manifest.join("src"), &mut h); // 前端源码（TS/Vite）
    dir_signature(&manifest.join("src-tauri").join("src"), &mut h); // Rust 源码
    hash_file(&manifest.join("src-tauri").join("Cargo.toml"), &mut h);
    hash_file(&manifest.join("src-tauri").join("Cargo.lock"), &mut h);
    hash_file(&manifest.join("src-tauri").join("tauri.conf.json"), &mut h);
    hash_file(&manifest.join("package.json"), &mut h);
    h.finish()
}

/// 递归地对目录内文件内容做哈希（排除噪声目录与生成文件）
fn dir_signature(dir: &Path, h: &mut DefaultHasher) {
    if let Ok(entries) = fs::read_dir(dir) {
        let mut names: Vec<_> = entries
            .flatten()
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .collect();
        names.sort();
        for name in names {
            if name == "node_modules"
                || name == "dist"
                || name == "target"
                || name == ".git"
                || name == "generated_version.rs"
            {
                continue;
            }
            name.hash(h);
            let p = dir.join(&name);
            if p.is_file() {
                hash_file(&p, h);
            } else if p.is_dir() {
                dir_signature(&p, h);
            }
        }
    }
}

/// 对单个文件内容做哈希（长度 + 字节）
fn hash_file(p: &Path, h: &mut DefaultHasher) {
    if let Ok(bytes) = fs::read(p) {
        (bytes.len() as u64).hash(h);
        h.write(&bytes);
    }
}

/// 读取历史构建状态
/// - 新格式 .build_state：「<date> <signature_u64> <count>」
/// - 迁移自旧 .build_count：「<date> <count>」（旧签名未知，视为已变更，下次构建将 +1）
fn read_state(path: &Path) -> (String, u64, u32) {
    if let Ok(s) = fs::read_to_string(path) {
        let mut it = s.split_whitespace();
        let d = it.next().unwrap_or("").to_string();
        let sig = it.next().and_then(|x| x.parse::<u64>().ok()).unwrap_or(0);
        let c = it.next().and_then(|x| x.parse::<u32>().ok()).unwrap_or(0);
        return (d, sig, c);
    }
    let old = path.with_file_name(".build_count");
    if let Ok(s) = fs::read_to_string(&old) {
        let mut it = s.split_whitespace();
        let d = it.next().unwrap_or("").to_string();
        let c = it.next().and_then(|x| x.parse::<u32>().ok()).unwrap_or(0);
        return (d, 0, c); // 旧签名未知 → 视为已变更，下次构建 +1
    }
    ("".to_string(), 0, 0)
}
