use std::fs;
use std::path::PathBuf;

fn main() {
    // Tauri 资源/配置处理（必须调用，否则 generate_context! 找不到资源）
    tauri_build::build();

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_default();
    let manifest = PathBuf::from(&manifest_dir);

    // 当天构建次数：每次构建自动 +1，用于在同一构建日期下区分不同构建产物。
    // 计数器存放在 target/ 下（已被 gitignore），不污染源码仓库；target 被 clean 后从 1 重新计。
    let counter_path = manifest.join("target").join(".build_count");
    let build_date = chrono::Local::now().format("%Y%m%d").to_string();
    let (prev_date, prev_count) = read_counter(&counter_path);
    let count = if prev_date == build_date { prev_count + 1 } else { 1 };
    if let Some(parent) = counter_path.parent() {
        let _ = fs::create_dir_all(parent);
    }
    let _ = fs::write(&counter_path, format!("{} {}\n", build_date, count));

    // 把完整版本号写入 generated_version.rs，models.rs 通过 include! 引入。
    // 关键点：用 include! 而非 env! —— 因为 env! 在 Cargo 增量编译下会被缓存跳过：
    // 当只有前端/无 Rust 改动时 build.rs 不重跑，env! 取的旧常量永远不变，计数永不递增。
    // 改为生成源文件后，文件内容随次数变化 → Cargo 必然重编译引用它的模块 → 版本号真正更新。
    // 注意：构建命令须 `touch build.rs` 强制本脚本每次都重跑（见构建流程），否则 Cargo 会缓存它。
    let gen_path = manifest.join("src").join("generated_version.rs");
    let _ = fs::write(
        &gen_path,
        format!(
            "// AUTO-GENERATED by build.rs — DO NOT EDIT\n\
             // 编译期固定注入：构建日期 + 当天构建次数（如 1.0.20260723.2）\n\
             pub const APP_BUILD_VERSION: &str = \"1.0.{}.{}\";\n",
            build_date, count
        ),
    );

    // 这两个 rerun-if-changed 让 Cargo 在文件变化时重跑脚本；
    // 但 build.rs 自身需在每次构建都被 touch（见构建命令），否则 Cargo 会缓存掉它导致计数不前进。
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/generated_version.rs");
}

/// 读取上一轮的「日期 次数」记录（纯文本，避免引入额外依赖）
fn read_counter(path: &PathBuf) -> (String, u32) {
    if let Ok(s) = fs::read_to_string(path) {
        let mut it = s.split_whitespace();
        let d = it.next().unwrap_or("").to_string();
        let c = it.next().and_then(|x| x.parse::<u32>().ok()).unwrap_or(0);
        (d, c)
    } else {
        ("".to_string(), 0)
    }
}
